### ISSUE TITLE
value not updating

### ISSUE THREAD

**Issue by 719media** [tinymce/tinymce-vue#196]
**What is the current behavior?**
Currently, tinymce vue binding to :value doesn't properly update when the value is changed

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io]
https://codesandbox.io/s/tinymcevue-forked-qboih

**What is the expected behavior?**
The first tinymce instance editor content would update to "changed" when the button is pressed, much like the v-model implementation does. However, I may not want to USE v-model, but just a value bind.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or tinymce-vue?**
I'm not sure, but this is the latest version of tinymce vue 3.2.6, and vue 2.6.12

**Comment by jscasca** [comment]
Hi @719media 

Thanks for bringing this up. It appears to be a bug that only binds the value listener when the `input` listener is present. That's why it works with the `v-model` alternative as it creates the `input` listener by default.

**Comment by jscasca** [comment]
This has been fixed in v3.2.8

**Comment by timberzzman** [comment]
Hi,

While looking for a solution to my problem, I came across this issue. I currently have the same issue, but in a higher version.
Here is a link to a codeSandbox that explains my situation:

[https://codesandbox.io/s/boring-zhukovsky-x4dvkp](https://codesandbox.io/s/boring-zhukovsky-x4dvkp)

I don't know if this is the same error, in any case the title describes the same situation.

Versions used:

Vue: 3.2.31
@tinymce/tinymce-vue: 4.0.6

**Comment by jscasca** [comment]
@timberzzman your code sandbox is not working for me, unfortunately. But looking at the code my guess is that you need your `editorValue` variable to be `ref` in order to watch for changes. Try
```
import { ref } from 'vue';
const editorValue = ref('initial content');
```

**Comment by timberzzman** [comment]
@jscasca Thanks for your fast response.

You were right, my example didn't work. I corrected it and imported TinyMCE to avoid the problem of the api-key not being present.

[https://codesandbox.io/s/boring-zhukovsky-x4dvkp](https://codesandbox.io/s/boring-zhukovsky-x4dvkp)

Unfortunately, the issue is still there. If I click on the button, the content of the editor is not modified.

I had to simplify my case, because on my side, my data are directly stored in a store with Pinia.

**Comment by jscasca** [comment]
@timberzzman I would have to check why the `value` property is not binding. In the meantime, can you use `v-model` instead of `:value`?

**Comment by jscasca** [comment]
This looks like it only happens when using the `<scrip setup>` instead of the `setup()` fn. Might need to dig around. Best to open a new ticket "Model :value not binding when using <scrip setup>"

**Comment by timberzzman** [comment]
Yeah, I will keep `v-model` for now. It's actually not an issue for my project, just a personal store access syntax.

I just created #303. Should I link this issue inside it ?

Thanks, @jscasca, for your time.
